# Generated by Django 4.2.2 on 2023-06-24 09:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocateHall',
            fields=[
                ('allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('semester', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], max_length=4)),
                ('no_seat', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(choices=[('1', 'ND I'), ('2', 'ND II'), ('3', 'HND I'), ('4', 'HND II')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatArrangement',
            fields=[
                ('seat_arrangement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('seat_no', models.IntegerField(blank=True, null=True)),
                ('allocation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_seat.allocatehall')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.AddField(
            model_name='allocatehall',
            name='hall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_seat.hall'),
        ),
        migrations.AddField(
            model_name='allocatehall',
            name='invigilator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.invigilator'),
        ),
    ]
