# Generated by Django 4.2.2 on 2023-06-27 14:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exam_seat', '0003_hall_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_title', models.CharField(max_length=7)),
                ('course_desc', models.CharField(max_length=100)),
                ('dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_seat.department')),
            ],
        ),
    ]
