# Generated by Django 4.2.2 on 2023-06-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_seat', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatehall',
            name='semester',
        ),
        migrations.AddField(
            model_name='allocatehall',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_seat.course'),
        ),
    ]
