# Generated by Django 4.2.2 on 2023-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_seat', '0005_remove_allocatehall_semester_allocatehall_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatehall',
            name='no_seat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
