# Generated by Django 4.2.2 on 2023-07-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_seat', '0006_alter_allocatehall_no_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatehall',
            name='no_seat',
        ),
    ]
