# Generated by Django 4.2.2 on 2023-07-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_seat', '0007_remove_allocatehall_no_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatehall',
            name='hall_id',
        ),
    ]
