# Generated by Django 4.2.2 on 2023-07-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_seat', '0008_remove_allocatehall_hall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatarrangement',
            name='hall_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_seat.hall'),
        ),
    ]
