# Generated by Django 4.2.2 on 2023-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilator',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
